apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kaas
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: kaas
spec:
  secretName: huawei-lb-annotator-certs
  dnsNames:
    - huawei-lb-annotator.default.svc
    - huawei-lb-annotator.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer