apiVersion: apps/v1
kind: Deployment
metadata:
  name: huawei-lb-annotator
  labels:
    app: huawei-lb-annotator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huawei-lb-annotator
  template:
    metadata:
      labels:
        app: huawei-lb-annotator
    spec:
      containers:
        - name: huawei-lb-annotator
          image: mixitd/huawei-lb-wh:0.2.12
          imagePullPolicy: Always
          args:
            - -certDir=/etc/webhook/certs
            - -port=8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: huawei-lb-annotator-certs
        - name: webhook-config
          configMap:
            name: huawei-lb-annotator-config