apiVersion: v1 
kind: Service 
metadata: 
  name: sample-03
  annotations:
    kubernetes.io/elb.autocreate: '{"type":"inner","name":"rnd-test-auto"}'
    # kubernetes.io/autocreate:
    #             '{
    #             "type": "public",
    #             "bandwidth_name": "mgmt01-ingress-xxxxx",
    #             "bandwidth_chargemode": "traffic",
    #             "bandwidth_size": 5,
    #             "bandwidth_sharetype": "PER",
    #             "eip_type": "5_bgp",
    #             "name": "mgmt01-ingress-xxxxx"
    #         }'

      # '{"type":"public",
      # "bandwidth_chargemode":"traffic",
      # "bandwidth_size":5,
      # "bandwidth_name":"bandwidth-test-001"
      # "bandwidth_sharetype":"PER",
      # "eip_type":"5_bgp",
      # "name":"rnd-test-auto-001"}'
    kubernetes.io/elb.class: union
    kubernetes.io/elb.enterpriseID: a104a57b-7345-4d3d-8289-48b8831ffb47
    kubernetes.io/elb.subnet-id: 5083f225-9bf8-48fa-9c8b-67bd9693c4c0
    kubernetes.io/session-affinity-mode: SOURCE_IP
spec: 
  type: LoadBalancer
  selector: 
    app: hello-world
  ports: 
  - port: 80 
    name: http